### ISSUE TITLE
Is there a way / setting to launch a specific room when you open the app?

### ISSUE THREAD

**Issue by gingemonster** [Meadowcottage/appear.in#1]

**Comment by Meadowcottage** [comment]
### There currently isn't any means of setting as specific room to launch when you open the app. Furthermore, I currently don't have plans to add this. 

> The point of the home page on [appear.in ](https://appear.in) is to allow people to just input any room name and go to it. If there was an account page to show you all your previous rooms, then I would make the app load to that by default as this would make life for returning users much simpler. But since there is not, I will continue to have the [appear.in ](https://appear.in) home page as the default page.

Sorry.
